from flask import Flask, request, jsonify, send_file
import io
import base64
import socket
import subprocess
import signal
import os
import threading
import time
import neurokit2 as nk

app = Flask(__name__)

current_wifi = {"ssid": None, "password": None}
process = None

# Buffers and latest values
ecg_buffer = []              # [{"ecg": value, "timestamp": X}, ...]
latest_plot = None           # Base64 plot generated by NeuroKit
latest_rr = None             # Latest respiration rate
latest_ecg_numbers = []      # Latest ECG array (for Flutter)
resp_rate_history = []       # Respiration history
glucose_buffer = []          # [{"glucose": value, "timestamp": X}]
process_thread = None
last_ecg_time = time.time()
rr_temp_buffer = []
last_rr_minute = time.time()

latest_glucose = {
    "value": None,
    "timestamp": None
}

# ------------------------------------------------------
# NeuroKit PROCESSING LOOP (runs inside the server)
# ------------------------------------------------------
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

def run_processing():
    global resp_rate_history, rr_temp_buffer, last_rr_minute, latest_rr, latest_plot, latest_ecg_numbers
    fs = 50               # ECG sampling rate
    window_sec = 30
    window_samples = fs * window_sec

    raw_buffer = []

    print("[NK] NeuroKit Processing Started")

    while True:
        time.sleep(1)

        # Append latest ECG samples
        if len(ecg_buffer) > 0:
            new_samples = [d["ecg"] for d in ecg_buffer[-200:]]
            raw_buffer.extend(new_samples)

        # Keep last 60 seconds only
        if len(raw_buffer) > window_samples * 2:
            raw_buffer = raw_buffer[-window_samples*2:]

        # Need at least 30 seconds of ECG
        if len(raw_buffer) < window_samples:
            continue

        # Build processing window
        window = np.array(raw_buffer[-window_samples:], dtype=float)
        window = pd.Series(window).interpolate().bfill().to_numpy()

        # -------------------------
        # Extract Respiration (EDR)
        # -------------------------
        try:
            # Extract respiration waveform from ECG
            edr = nk.ecg_rsp(window, sampling_rate=fs)

            # Detect breathing peaks
            rsp_peaks = nk.rsp_peaks(edr, sampling_rate=fs)

            # Compute respiration rate (breaths per minute)
            breathing_rate = nk.signal_rate(rsp_peaks, sampling_rate=fs)

            # Average rate inside this window
            latest_rr = float(np.mean(breathing_rate)) if len(breathing_rate) > 0 else None

            # ---------------------------------------------------------
            # 1-minute averaging logic
            # ---------------------------------------------------------
            if latest_rr is not None:
                rr_temp_buffer.append(latest_rr)

            # Every 60 seconds → compute 1-minute average
            if time.time() - last_rr_minute >= 60:

                if len(rr_temp_buffer) > 0:
                    minute_avg = sum(rr_temp_buffer) / len(rr_temp_buffer)
                    resp_rate_history.append(round(minute_avg, 2))
                    print("[RR] 1-minute average:", round(minute_avg, 2))

                # Reset buffer & timestamp
                rr_temp_buffer.clear()
                last_rr_minute = time.time()

                # Keep last 24 hours
                if len(resp_rate_history) > 1440:
                    resp_rate_history = resp_rate_history[-1440:]

        except Exception as e:
            print("[NK] Respiration Error:", e)
            latest_rr = None

        # -------------------------------------------------
        # Last ECG Numbers
        # -------------------------------------------------
        latest_ecg_numbers = window[-500:].tolist()

        # -------------------------------------------------
        # Plot ECG
        # -------------------------------------------------
        try:
            fig, ax = plt.subplots(figsize=(6, 2))
            ax.plot(window[-500:])
            ax.set_title("ECG (last 10 seconds)")
            fig.tight_layout()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            latest_plot = base64.b64encode(buf.read()).decode()

            plt.close(fig)
        except Exception as e:
            print("[NK] Plot Error:", e)
            latest_plot = None

def ecg_auto_clear_loop():
    global latest_ecg_numbers, last_ecg_time

    while True:
        time.sleep(30)  # check every 30 seconds
        now = time.time()

        # 5 minutes = 300 seconds
        if now - last_ecg_time > 300:
            if len(latest_ecg_numbers) > 0:
                print("[AUTO CLEAR] No ECG data for 5 minutes → clearing latest_ecg_numbers")
                latest_ecg_numbers.clear()

# ------------------------------------------------------
# START PROCESSING SCRIPT
# ------------------------------------------------------
@app.route('/start_processing', methods=['POST'])
def start_processing():
    global process_thread
    if not process_thread or not process_thread.is_alive():
        process_thread = threading.Thread(target=run_processing, daemon=True)
        process_thread.start()
        return jsonify({"status": "processing started"})
    return jsonify({"status": "already running"})


# ------------------------------------------------------
# RAW ECG DATA ENDPOINTS (USED BY ESP32 & FLUTTER)
# ------------------------------------------------------
@app.route('/data', methods=['POST'])
def receive_data():
    global latest_ecg_numbers, last_ecg_time, latest_glucose, glucose_buffer

    data = request.get_json()

    if not data:
        return jsonify({"status": "error", "message": "bad JSON"}), 400

    ecg = data.get("ecg")
    glucose = data.get("glucose")
    timestamp = data.get("timestamp", time.time())

    # ===================== PROCESS GLUCOSE FIRST ======================
    if glucose is not None and glucose != 0:
        latest_glucose["value"] = glucose
        latest_glucose["timestamp"] = timestamp
        glucose_buffer.append({"glucose": glucose, "timestamp": timestamp})
        print(f"[GLUCOSE] Updated glucose: {glucose}")

    # ===================== PROCESS ECG (batch or single) ==============
    if isinstance(ecg, list):
        # batch of ECG values
        for v in ecg:
            ecg_buffer.append({"ecg": v, "timestamp": timestamp})
            latest_ecg_numbers.append(v)

    else:
        # single ECG value (or the glucose packet's ecg=0)
        if isinstance(ecg, (int, float)):
            ecg_buffer.append({"ecg": ecg, "timestamp": timestamp})
            latest_ecg_numbers.append(ecg)

    last_ecg_time = time.time()

    return jsonify({"status": "ok"})

@app.route('/ecgclear', methods=['POST'])
def clear_ecg_numbers():
    global latest_ecg_numbers, ecg_buffer

    latest_ecg_numbers.clear()   # clear numbers sent to Flutter
    ecg_buffer.clear()           # optional: clear raw ECG buffer

    return jsonify({"status": "ecg numbers cleared"})

@app.route('/ecg', methods=['GET'])
def get_ecg():
    return jsonify(ecg_buffer[-500:])


@app.route('/clear', methods=['POST'])
def clear_buffer():
    ecg_buffer.clear()
    latest_ecg_numbers.clear()
    return jsonify({"status": "cleared"})


# ------------------------------------------------------
# ECG PLOT ENDPOINT
# ------------------------------------------------------
@app.route('/ecg_plot', methods=['GET'])
def show_ecg_plot():
    global latest_plot
    if latest_plot is None:
        return "No plot available yet", 404
    img_bytes = base64.b64decode(latest_plot)
    return send_file(io.BytesIO(img_bytes), mimetype='image/png')


@app.route('/ecg_plot', methods=['POST'])
def receive_ecg_plot():
    global latest_plot
    data = request.get_json()
    latest_plot = data.get("plot")
    return jsonify({"status": "ok"})


# ------------------------------------------------------
# RESPIRATION RATE ENDPOINT
# ------------------------------------------------------
@app.route('/resp_rate', methods=['GET'])
def show_resp_rate():
    global resp_rate_history

    # need at least one value
    if len(resp_rate_history) == 0:
        return jsonify({"resp_rate": None}), 404

    # get last 60 seconds (or fewer if not available yet)
    last_minute = resp_rate_history[-60:]

    avg_rr = sum(last_minute) / len(last_minute)

    return jsonify({
        "resp_rate": round(avg_rr, 2),
        "samples_used": len(last_minute)
    })



@app.route('/resp_rate', methods=['POST'])
def receive_resp_rate():
    global latest_rr
    data = request.get_json()
    latest_rr = data.get("resp_rate")
    return jsonify({"status": "ok"})


# ------------------------------------------------------
# ECG NUMBERS ENDPOINT
# ------------------------------------------------------
@app.route('/ecgnumbers', methods=['GET'])
def show_ecg_numbers():
    global latest_ecg_numbers
    if not latest_ecg_numbers:
        return jsonify({"numbers": []}), 404
    return jsonify({"numbers": latest_ecg_numbers})


@app.route('/ecgnumbers', methods=['POST'])
def receive_ecg_numbers():
    global latest_ecg_numbers
    data = request.get_json()
    latest_ecg_numbers = data.get("numbers", [])
    return jsonify({"status": "ok"})
    global last_ecg_time
    last_ecg_time = time.time()


# ------------------------------------------------------
# RESP HISTORY
# ------------------------------------------------------
@app.route('/resp_history', methods=['GET'])
def show_resp_history():
    global resp_rate_history
    if not resp_rate_history:
        return jsonify({"resp_history": []}), 404
    return jsonify({"resp_history": resp_rate_history})


@app.route('/resp_history', methods=['POST'])
def receive_resp_history():
    global resp_rate_history
    data = request.get_json()
    resp_rate_history = data.get("resp_history", [])
    return jsonify({"status": "ok"})


# ------------------------------------------------------
# GLUCOSE ENDPOINTS
# ------------------------------------------------------
@app.route('/glucose', methods=['GET'])
def show_glucose_numbers():
    global latest_glucose
    if latest_glucose["value"] is None:
        return jsonify({"glucose": None}), 404

    return jsonify({
        "glucose": latest_glucose["value"],
        "timestamp": latest_glucose["timestamp"]
    })


@app.route('/glucose', methods=['POST'])
def receive_glucose_numbers():
    global latest_glucose, glucose_buffer
    data = request.get_json()

    glucose = data.get("glucose")
    timestamp = data.get("timestamp")

    if glucose is not None:
        latest_glucose["value"] = glucose
        latest_glucose["timestamp"] = timestamp
        glucose_buffer.append({"glucose": glucose, "timestamp": timestamp})

        print(f"Updated glucose via POST: {glucose}")

    return jsonify({"status": "ok"})


@app.route('/glucose_history', methods=['GET'])
def glucose_history():
    if len(glucose_buffer) == 0:
        return jsonify({"glucose_history": []}), 404

    # extract only glucose values
    values = [entry["glucose"] for entry in glucose_buffer]

    return jsonify({"glucose_history": values})


# ------------------------------------------------------
# TEST ROUTE
# ------------------------------------------------------
@app.route('/test')
def home():
    return "hello world"


# ------------------------------------------------------
# START SERVER
# ------------------------------------------------------
if __name__ == '__main__':
    threading.Thread(target=ecg_auto_clear_loop, daemon=True).start()
    app.run(host="0.0.0.0", port=8000)


